// Generated by gencpp from file hrc/tensor_flowResponse.msg
// DO NOT EDIT!


#ifndef HRC_MESSAGE_TENSOR_FLOWRESPONSE_H
#define HRC_MESSAGE_TENSOR_FLOWRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hrc
{
template <class ContainerAllocator>
struct tensor_flowResponse_
{
  typedef tensor_flowResponse_<ContainerAllocator> Type;

  tensor_flowResponse_()
    : prediction_output()  {
    }
  tensor_flowResponse_(const ContainerAllocator& _alloc)
    : prediction_output(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int64_t, typename ContainerAllocator::template rebind<int64_t>::other >  _prediction_output_type;
  _prediction_output_type prediction_output;




  typedef boost::shared_ptr< ::hrc::tensor_flowResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrc::tensor_flowResponse_<ContainerAllocator> const> ConstPtr;

}; // struct tensor_flowResponse_

typedef ::hrc::tensor_flowResponse_<std::allocator<void> > tensor_flowResponse;

typedef boost::shared_ptr< ::hrc::tensor_flowResponse > tensor_flowResponsePtr;
typedef boost::shared_ptr< ::hrc::tensor_flowResponse const> tensor_flowResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hrc::tensor_flowResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hrc::tensor_flowResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hrc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hrc::tensor_flowResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hrc::tensor_flowResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrc::tensor_flowResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrc::tensor_flowResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrc::tensor_flowResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrc::tensor_flowResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hrc::tensor_flowResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b902da4ca3a9e62ff9c4f014b8c7ab06";
  }

  static const char* value(const ::hrc::tensor_flowResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb902da4ca3a9e62fULL;
  static const uint64_t static_value2 = 0xf9c4f014b8c7ab06ULL;
};

template<class ContainerAllocator>
struct DataType< ::hrc::tensor_flowResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hrc/tensor_flowResponse";
  }

  static const char* value(const ::hrc::tensor_flowResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hrc::tensor_flowResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64[] prediction_output\n\
";
  }

  static const char* value(const ::hrc::tensor_flowResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hrc::tensor_flowResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.prediction_output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tensor_flowResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrc::tensor_flowResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hrc::tensor_flowResponse_<ContainerAllocator>& v)
  {
    s << indent << "prediction_output[]" << std::endl;
    for (size_t i = 0; i < v.prediction_output.size(); ++i)
    {
      s << indent << "  prediction_output[" << i << "]: ";
      Printer<int64_t>::stream(s, indent + "  ", v.prediction_output[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRC_MESSAGE_TENSOR_FLOWRESPONSE_H
