// Generated by gencpp from file hrc/tensor_flowRequest.msg
// DO NOT EDIT!


#ifndef HRC_MESSAGE_TENSOR_FLOWREQUEST_H
#define HRC_MESSAGE_TENSOR_FLOWREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace hrc
{
template <class ContainerAllocator>
struct tensor_flowRequest_
{
  typedef tensor_flowRequest_<ContainerAllocator> Type;

  tensor_flowRequest_()
    : prediction_input()  {
    }
  tensor_flowRequest_(const ContainerAllocator& _alloc)
    : prediction_input(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _prediction_input_type;
  _prediction_input_type prediction_input;




  typedef boost::shared_ptr< ::hrc::tensor_flowRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hrc::tensor_flowRequest_<ContainerAllocator> const> ConstPtr;

}; // struct tensor_flowRequest_

typedef ::hrc::tensor_flowRequest_<std::allocator<void> > tensor_flowRequest;

typedef boost::shared_ptr< ::hrc::tensor_flowRequest > tensor_flowRequestPtr;
typedef boost::shared_ptr< ::hrc::tensor_flowRequest const> tensor_flowRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hrc::tensor_flowRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hrc::tensor_flowRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hrc

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hrc::tensor_flowRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hrc::tensor_flowRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrc::tensor_flowRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hrc::tensor_flowRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrc::tensor_flowRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hrc::tensor_flowRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hrc::tensor_flowRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2fbaeb7f415f285ee82ff6bc6b802be5";
  }

  static const char* value(const ::hrc::tensor_flowRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2fbaeb7f415f285eULL;
  static const uint64_t static_value2 = 0xe82ff6bc6b802be5ULL;
};

template<class ContainerAllocator>
struct DataType< ::hrc::tensor_flowRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hrc/tensor_flowRequest";
  }

  static const char* value(const ::hrc::tensor_flowRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hrc::tensor_flowRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] prediction_input\n\
";
  }

  static const char* value(const ::hrc::tensor_flowRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hrc::tensor_flowRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.prediction_input);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct tensor_flowRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hrc::tensor_flowRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hrc::tensor_flowRequest_<ContainerAllocator>& v)
  {
    s << indent << "prediction_input[]" << std::endl;
    for (size_t i = 0; i < v.prediction_input.size(); ++i)
    {
      s << indent << "  prediction_input[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.prediction_input[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HRC_MESSAGE_TENSOR_FLOWREQUEST_H
